export const kanjiBlocks = {
    1: [
      { kanji: "一", hiragana: ["いち"], romaji: ["ichi"], meaning: ["one"] },
      { kanji: "二", hiragana: ["に"], romaji: ["ni"], meaning: ["two"] },
      { kanji: "三", hiragana: ["さん"], romaji: ["san"], meaning: ["three"] },
      { kanji: "四", hiragana: ["し", "よん"], romaji: ["shi", "yon"], meaning: ["four"] },
      { kanji: "五", hiragana: ["ご"], romaji: ["go"], meaning: ["five"] },
      { kanji: "六", hiragana: ["ろく"], romaji: ["roku"], meaning: ["six"] },
      { kanji: "七", hiragana: ["しち", "なな"], romaji: ["shichi", "nana"], meaning: ["seven"] },
      { kanji: "八", hiragana: ["はち"], romaji: ["hachi"], meaning: ["eight"] },
      { kanji: "九", hiragana: ["く", "きゅう"], romaji: ["ku", "kyuu"], meaning: ["nine"] },
      { kanji: "十", hiragana: ["じゅう"], romaji: ["juu"], meaning: ["ten"] },
      { kanji: "人", hiragana: ["ひと"], romaji: ["hito"], meaning: ["person"] },
      { kanji: "山", hiragana: ["やま"], romaji: ["yama"], meaning: ["mountain"] },
      { kanji: "日よう日", hiragana: ["にちようび"], romaji: ["nichiyoubi"], meaning: ["sunday"] },
      { kanji: "タイ人", hiragana: ["タイじん"], romaji: ["taijin"], meaning: ["thai person"] }
    ],
  
    2: [
      { kanji: "白い", hiragana: ["しろい"], romaji: ["shiroi"], meaning: ["white"] },
      { kanji: "百", hiragana: ["ひゃく"], romaji: ["hyaku"], meaning: ["hundred"] },
      { kanji: "千", hiragana: ["せん"], romaji: ["sen"], meaning: ["thousand"] },
      { kanji: "万", hiragana: ["まん"], romaji: ["man"], meaning: ["ten thousand"] },
      { kanji: "十円", hiragana: ["じゅうえん"], romaji: ["juuen"], meaning: ["ten yen"] },
      { kanji: "月よう日", hiragana: ["げつようび"], romaji: ["getsuyoubi"], meaning: ["monday"] },
      { kanji: "火よう日", hiragana: ["かようび"], romaji: ["kayoubi"], meaning: ["tuesday"] },
      { kanji: "水よう日", hiragana: ["すいようび"], romaji: ["suiyoubi"], meaning: ["wednesday"] },
      { kanji: "木よう日", hiragana: ["もくようび"], romaji: ["mokuyoubi"], meaning: ["thursday"] },
      { kanji: "金よう日", hiragana: ["きんようび"], romaji: ["kinyoubi"], meaning: ["friday"] },
      { kanji: "土よう日", hiragana: ["どようび"], romaji: ["doyoubi"], meaning: ["saturday"] },
      { kanji: "子ども", hiragana: ["こども"], romaji: ["kodomo"], meaning: ["child"] },
      { kanji: "一才", hiragana: ["いっさい"], romaji: ["issai"], meaning: ["1 year old"] },
      { kanji: "四月", hiragana: ["しがつ"], romaji: ["shigatsu"], meaning: ["april"] },
      { kanji: "四じ", hiragana: ["よじ"], romaji: ["yoji"], meaning: ["4 o'clock"] },
      { kanji: "この日", hiragana: ["このひ"], romaji: ["kono hi"], meaning: ["this day", "today"] },
      { kanji: "この月", hiragana: ["このつき"], romaji: ["kono tsuki"], meaning: ["this month"] },
      { kanji: "二十才", hiragana: ["はたち"], romaji: ["hatachi"], meaning: ["20 years old"] }
    ],
  
    3: [
      { kanji: "明るい", hiragana: ["あかるい"], romaji: ["akarui"], meaning: ["bright"] },
      { kanji: "古い", hiragana: ["ふるい"], romaji: ["furui"], meaning: ["old"] },
      { kanji: "この方", hiragana: ["このかた"], romaji: ["kono kata"], meaning: ["this person"] },
      { kanji: "学生", hiragana: ["がくせい"], romaji: ["gakusei"], meaning: ["student"] },
      { kanji: "一年", hiragana: ["いちねん"], romaji: ["ichinen"], meaning: ["1 year"] },
      { kanji: "早く", hiragana: ["はやく"], romaji: ["hayaku"], meaning: ["early", "quickly"] },
      { kanji: "寺", hiragana: ["てら"], romaji: ["tera"], meaning: ["temple"] },
      { kanji: "春", hiragana: ["はる"], romaji: ["haru"], meaning: ["spring"] },
      { kanji: "秋", hiragana: ["あき"], romaji: ["aki"], meaning: ["autumn"] },
      { kanji: "冬", hiragana: ["ふゆ"], romaji: ["fuyu"], meaning: ["winter"] },
      { kanji: "夕方", hiragana: ["ゆうがた"], romaji: ["yuugata"], meaning: ["evening"] },
      { kanji: "上", hiragana: ["うえ"], romaji: ["ue"], meaning: ["up", "above"] },
      { kanji: "生年月日", hiragana: ["せいねんがっぴ"], romaji: ["seinengappi"], meaning: ["birthdate"] },
      { kanji: "年", hiragana: ["とし"], romaji: ["toshi"], meaning: ["year"] },
      { kanji: "一日", hiragana: ["ついたち"], romaji: ["tsuitachi"], meaning: ["1st day"] },
      { kanji: "二日", hiragana: ["ふつか"], romaji: ["futsuka"], meaning: ["2nd day"] },
      { kanji: "三日", hiragana: ["みっか"], romaji: ["mikka"], meaning: ["3rd day"] },
      { kanji: "四日", hiragana: ["よっか"], romaji: ["yokka"], meaning: ["4th day"] },
      { kanji: "五日", hiragana: ["いつか"], romaji: ["itsuka"], meaning: ["5th day"] },
      { kanji: "六日", hiragana: ["むいか"], romaji: ["muika"], meaning: ["6th day"] },
      { kanji: "七日", hiragana: ["なのか"], romaji: ["nanoka"], meaning: ["7th day"] },
      { kanji: "八日", hiragana: ["ようか"], romaji: ["youka"], meaning: ["8th day"] },
      { kanji: "九日", hiragana: ["ここのか"], romaji: ["kokonoka"], meaning: ["9th day"] },
      { kanji: "十日", hiragana: ["とおか"], romaji: ["tooka"], meaning: ["10th day"] },
      { kanji: "二十日", hiragana: ["はつか"], romaji: ["hatsuka"], meaning: ["20th day"] }
    ],
    4: [
      { kanji: "下", hiragana: ["した"], romaji: ["shita"], meaning: ["under", "below"] },
      { kanji: "中", hiragana: ["なか"], romaji: ["naka"], meaning: ["inside", "middle"] },
      { kanji: "外", hiragana: ["そと"], romaji: ["soto"], meaning: ["outside"] },
      { kanji: "小さい", hiragana: ["ちいさい"], romaji: ["chiisai"], meaning: ["small"] },
      { kanji: "大きい", hiragana: ["おおきい"], romaji: ["ookii"], meaning: ["big", "large"] },
      { kanji: "犬", hiragana: ["いぬ"], romaji: ["inu"], meaning: ["dog"] },
      { kanji: "牛", hiragana: ["うし"], romaji: ["ushi"], meaning: ["cow", "ox"] },
      { kanji: "馬", hiragana: ["うま"], romaji: ["uma"], meaning: ["horse"] },
      { kanji: "門", hiragana: ["もん"], romaji: ["mon"], meaning: ["gate"] },
      { kanji: "間", hiragana: ["あいだ"], romaji: ["aida"], meaning: ["between", "interval"] },
      { kanji: "池", hiragana: ["いけ"], romaji: ["ike"], meaning: ["pond"] },
      { kanji: "本", hiragana: ["ほん"], romaji: ["hon"], meaning: ["book", "origin"] },
      { kanji: "川", hiragana: ["かわ"], romaji: ["kawa"], meaning: ["river"] },
      { kanji: "木", hiragana: ["き"], romaji: ["ki"], meaning: ["tree", "wood"] },
      { kanji: "一人", hiragana: ["ひとり"], romaji: ["hitori"], meaning: ["one person", "alone"] },
      { kanji: "二人", hiragana: ["ふたり"], romaji: ["futari"], meaning: ["two people"] },
      { kanji: "三人", hiragana: ["さんにん"], romaji: ["sannin"], meaning: ["three people"] },
      { kanji: "四人", hiragana: ["よにん"], romaji: ["yonin"], meaning: ["four people"] },
      { kanji: "お金", hiragana: ["おかね"], romaji: ["okane"], meaning: ["money"] },
      { kanji: "日本", hiragana: ["にほん"], romaji: ["nihon"], meaning: ["japan"] },
      { kanji: "一本", hiragana: ["いっぽん"], romaji: ["ippon"], meaning: ["one long object"] },
      { kanji: "三本", hiragana: ["さんぼん"], romaji: ["sanbon"], meaning: ["three long objects"] }
    ],
    
  };