export const vocabChap = {
 1: [
    { vocab: ["おんなのひと"], meaning: ["woman","female"] },
    { vocab: ["おとこのひと"], meaning: ["man","male"] },
    { vocab: ["ひと"], meaning: ["person"] },
    { vocab: ["かばん"], meaning: ["bag"] },
    { vocab: ["かぎ"], meaning: ["key"] },
    { vocab: ["へや"], meaning: ["room"] },
    { vocab: ["とけい"], meaning: ["clock", "watch"] },
    { vocab: ["ほん"], meaning: ["book"] },
    { vocab: ["しんぶん"], meaning: ["newspaper"] },
    { vocab: ["えいご"], meaning: ["english language"] },
    { vocab: ["くるま", "じどうしゃ"], meaning: ["car", "automobile"] },
    { vocab: ["じてんしゃ"], meaning: ["bicycle"] },
    { vocab: ["きって"], meaning: ["stamp"] },
    { vocab: ["つくえ"], meaning: ["desk"] },
    { vocab: ["いす"], meaning: ["chair"] },
    { vocab: ["えんぴつ"], meaning: ["pencil"] },
    { vocab: ["ボールペン"], meaning: ["ballpoint pen"] },
    { vocab: ["タイ"], meaning: ["thailand"] },
    { vocab: ["イギリス"], meaning: ["england"] },
    { vocab: ["ちゅうごく"], meaning: ["china"] },
    { vocab: ["だれ"], meaning: ["who"] },
    { vocab: ["どれ"], meaning: ["which"] },
    { vocab: ["なに"], meaning: ["what"] }
  ],

  2:  [
    { vocab: ["がっこう"], meaning: ["school"] },
    { vocab: ["きょうしつ"], meaning: ["classroom"] },
    { vocab: ["しょくどう"], meaning: ["dining room"] },
    { vocab: ["しょっけん"], meaning: ["meal ticket"] },
    { vocab: ["パン"], meaning: ["bread"] },
    { vocab: ["ぎゅうにゅう"], meaning: ["cow's milk"] },
    { vocab: ["にわ"], meaning: ["garden"] },
    { vocab: ["たてもの"], meaning: ["building"] },
    { vocab: ["りょう"], meaning: ["dormitory"] },
    { vocab: ["びょういん"], meaning: ["hospital"] },
    { vocab: ["じむしょ"], meaning: ["office"] },
    { vocab: ["としょしつ"], meaning: ["library"] },
    { vocab: ["たいいくかん"], meaning: ["gymnasium"] },
    { vocab: ["うち"], meaning: ["house", "home"] },
    { vocab: ["かみ"], meaning: ["paper"] },
    { vocab: ["さかな"], meaning: ["fish"] },
    { vocab: ["やま"], meaning: ["mountain"] },
    { vocab: ["いま"], meaning: ["now"] },
    { vocab: ["どこ"], meaning: ["where"] },
    { vocab: ["どんな"], meaning: ["what kind"] },
    { vocab: ["いくら"], meaning: ["how much"] },
    { vocab: ["なんじ"], meaning: ["what time"] },
    { vocab: ["ここ"], meaning: ["here"] },
    { vocab: ["そこ"], meaning: ["there"] },
    { vocab: ["あそこ"], meaning: ["over there"] },
    { vocab: ["ちいさい"], meaning: ["small"] },
    { vocab: ["あかい"], meaning: ["red"] },
    { vocab: ["しろい"], meaning: ["white"] },
    { vocab: ["おおきい"], meaning: ["big"] },
    { vocab: ["たかい"], meaning: ["expensive", "high"] },
    { vocab: ["やすい"], meaning: ["cheap"] },
    { vocab: ["あたらしい"], meaning: ["new"] },
    { vocab: ["きいろい"], meaning: ["yellow"] },
    { vocab: ["ひくい"], meaning: ["low"] },
    { vocab: ["くらい"], meaning: ["dark"] },
    { vocab: ["あかるい"], meaning: ["bright"] },
    { vocab: ["ふるい"], meaning: ["old"] },
    { vocab: ["あおい"], meaning: ["blue", "green"] },
    { vocab: ["くろい"], meaning: ["black"] },
    { vocab: ["そして"], meaning: ["and", "and then"] },
    { vocab: ["はん"], meaning: ["half-past"] },
    { vocab: ["ごふんまえ"], meaning: ["five minutes before"] },
    { vocab: ["ろっぷんすぎ"], meaning: ["six minutes after"] }
  ],
  
}