export const vocabChap = {
 1: [
    { vocab: ["おんなのひと"], meaning: ["woman","female"] },
    { vocab: ["おとこのひと"], meaning: ["man","male"] },
    { vocab: ["ひと"], meaning: ["person"] },
    { vocab: ["かばん"], meaning: ["bag"] },
    { vocab: ["かぎ"], meaning: ["key"] },
    { vocab: ["へや"], meaning: ["room"] },
    { vocab: ["とけい"], meaning: ["clock", "watch"] },
    { vocab: ["ほん"], meaning: ["book"] },
    { vocab: ["しんぶん"], meaning: ["newspaper"] },
    { vocab: ["えいご"], meaning: ["english language"] },
    { vocab: ["くるま", "じどうしゃ"], meaning: ["car", "automobile"] },
    { vocab: ["じてんしゃ"], meaning: ["bicycle"] },
    { vocab: ["きって"], meaning: ["stamp"] },
    { vocab: ["つくえ"], meaning: ["desk"] },
    { vocab: ["いす"], meaning: ["chair"] },
    { vocab: ["えんぴつ"], meaning: ["pencil"] },
    { vocab: ["ボールペン"], meaning: ["ballpoint pen"] },
    { vocab: ["タイ"], meaning: ["thailand"] },
    { vocab: ["イギリス"], meaning: ["england"] },
    { vocab: ["ちゅうごく"], meaning: ["china"] },
    { vocab: ["だれ"], meaning: ["who"] },
    { vocab: ["どれ"], meaning: ["which"] },
    { vocab: ["なに"], meaning: ["what"] }
  ],

  2:  [
    { vocab: ["がっこう"], meaning: ["school"] },
    { vocab: ["きょうしつ"], meaning: ["classroom"] },
    { vocab: ["しょくどう"], meaning: ["dining room"] },
    { vocab: ["しょっけん"], meaning: ["meal ticket"] },
    { vocab: ["パン"], meaning: ["bread"] },
    { vocab: ["ぎゅうにゅう"], meaning: ["cow's milk"] },
    { vocab: ["にわ"], meaning: ["garden"] },
    { vocab: ["たてもの"], meaning: ["building"] },
    { vocab: ["りょう"], meaning: ["dormitory"] },
    { vocab: ["びょういん"], meaning: ["hospital"] },
    { vocab: ["じむしょ"], meaning: ["office"] },
    { vocab: ["としょしつ"], meaning: ["library"] },
    { vocab: ["たいいくかん"], meaning: ["gymnasium"] },
    { vocab: ["うち"], meaning: ["house", "home"] },
    { vocab: ["かみ"], meaning: ["paper"] },
    { vocab: ["さかな"], meaning: ["fish"] },
    { vocab: ["やま"], meaning: ["mountain"] },
    { vocab: ["いま"], meaning: ["now"] },
    { vocab: ["どこ"], meaning: ["where"] },
    { vocab: ["どんな"], meaning: ["what kind"] },
    { vocab: ["いくら"], meaning: ["how much"] },
    { vocab: ["なんじ"], meaning: ["what time"] },
    { vocab: ["ここ"], meaning: ["here"] },
    { vocab: ["そこ"], meaning: ["there"] },
    { vocab: ["あそこ"], meaning: ["over there"] },
    { vocab: ["ちいさい"], meaning: ["small"] },
    { vocab: ["あかい"], meaning: ["red"] },
    { vocab: ["しろい"], meaning: ["white"] },
    { vocab: ["おおきい"], meaning: ["big"] },
    { vocab: ["たかい"], meaning: ["expensive", "high"] },
    { vocab: ["やすい"], meaning: ["cheap"] },
    { vocab: ["あたらしい"], meaning: ["new"] },
    { vocab: ["きいろい"], meaning: ["yellow"] },
    { vocab: ["ひくい"], meaning: ["low"] },
    { vocab: ["くらい"], meaning: ["dark"] },
    { vocab: ["あかるい"], meaning: ["bright"] },
    { vocab: ["ふるい"], meaning: ["old"] },
    { vocab: ["あおい"], meaning: ["blue", "green"] },
    { vocab: ["くろい"], meaning: ["black"] },
    { vocab: ["そして"], meaning: ["and", "and then"] },
    { vocab: ["はん"], meaning: ["half-past"] },
    { vocab: ["ごふんまえ"], meaning: ["five minutes before"] },
    { vocab: ["ろっぷんすぎ"], meaning: ["six minutes after"] }
  ],

  3: [
    { vocab: ["おかし"], meaning: ["sweets", "candy", "snacks"] },
    { vocab: ["コーヒー"], meaning: ["coffee"] },
    { vocab: ["こうちゃ"], meaning: ["black tea"] },
    { vocab: ["しょくじ"], meaning: ["meal", "dining"] },
    { vocab: ["やすみ"], meaning: ["holiday"] },
    { vocab: ["ざっし"], meaning: ["magazine"] },
    { vocab: ["えいが"], meaning: ["movie"] },
    { vocab: ["えいがかん"], meaning: ["movie theatre"] },
    { vocab: ["てがみ"], meaning: ["letter"] },
    { vocab: ["まいにち"], meaning: ["everyday"] },
    { vocab: ["あさって"], meaning: ["day after tomorrow"] },
    { vocab: ["きのう"], meaning: ["yesterday"] },
    { vocab: ["きょう"], meaning: ["today"] },
    { vocab: ["あした"], meaning: ["tomorrow"] },
    { vocab: ["おととい"], meaning: ["day before yesterday"] },
    { vocab: ["あさ"], meaning: ["morning"] },
    { vocab: ["ひる"], meaning: ["noon"] },
    { vocab: ["よる"], meaning: ["night"] },
    { vocab: ["ゆうがた"], meaning: ["early evening"] },
    { vocab: ["ばん"], meaning: ["evening", "night"] },
    { vocab: ["まいしゅう"], meaning: ["every week"] },
    { vocab: ["せんせんしゅう"], meaning: ["week before last"] },
    { vocab: ["せんしゅう"], meaning: ["last week"] },
    { vocab: ["こんしゅう"], meaning: ["this week"] },
    { vocab: ["らいしゅう"], meaning: ["next week"] },
    { vocab: ["さらいしゅう"], meaning: ["week after next"] },
    { vocab: ["べんきょうします"], meaning: ["study"] },
    { vocab: ["のみます"], meaning: ["drink"] },
    { vocab: ["たべます"], meaning: ["eat"] },
    { vocab: ["つくります"], meaning: ["make"] },
    { vocab: ["します"], meaning: ["do"] },
    { vocab: ["あそびます"], meaning: ["play"] },
    { vocab: ["うたいます"], meaning: ["sing"] },
    { vocab: ["かきます"], meaning: ["write"] },
    { vocab: ["ききます"], meaning: ["listen"] },
    { vocab: ["よみます"], meaning: ["read"] },
    { vocab: ["みます"], meaning: ["see", "watch"] },
    { vocab: ["おわります"], meaning: ["end"] },
    { vocab: ["はじまります"], meaning: ["start", "begin"] },
    { vocab: ["ねます"], meaning: ["sleep"] },
    { vocab: ["おきます"], meaning: ["get up", "wake up"] },
    { vocab: ["ときどき"], meaning: ["sometimes"] },
    { vocab: ["ね"], meaning: ["isn't it?"] },
    { vocab: ["じゅうじごろ"], meaning: ["around 10 o'clock"] }
  ],
  4: [
    { vocab: ["こども"], meaning: ["child"] },
    { vocab: ["おとな"], meaning: ["adult"] },
    { vocab: ["かいしゃ"], meaning: ["company", "business company"] },
    { vocab: ["しごと"], meaning: ["work", "job"] },
    { vocab: ["こうえん"], meaning: ["park"] },
    { vocab: ["けん"], meaning: ["admission ticket"] },
    { vocab: ["きっぷ"], meaning: ["ticket"] },
    { vocab: ["しゃしん"], meaning: ["photograph", "picture"] },
    { vocab: ["がいこく"], meaning: ["foreign country"] },
    { vocab: ["くに"], meaning: ["country", "nation"] },
    { vocab: ["りゅうがくせい"], meaning: ["foreign student"] },
    { vocab: ["ほんや"], meaning: ["bookstore"] },
    { vocab: ["とし"], meaning: ["year", "age"] },
    { vocab: ["たんじょうび"], meaning: ["date of birth"] },
    { vocab: ["はたち"], meaning: ["20 years old"] },
    { vocab: ["ゆうびんきょく"], meaning: ["post office"] },
    { vocab: ["ぎんこう"], meaning: ["bank"] },
    { vocab: ["みせ"], meaning: ["store", "shop"] },
    { vocab: ["ひ"], meaning: ["day"] },
    { vocab: ["まいつき"], meaning: ["every month"] },
    { vocab: ["まいとし"], meaning: ["every year"] },
    { vocab: ["たんじょうび"], meaning: ["birthday"] },
    { vocab: ["ついたち"], meaning: ["1st day"] },
    { vocab: ["ふつか"], meaning: ["2nd day"] },
    { vocab: ["みっか"], meaning: ["3rd day"] },
    { vocab: ["よっか"], meaning: ["4th day"] },
    { vocab: ["いつか"], meaning: ["5th day"] },
    { vocab: ["むいか"], meaning: ["6th day"] },
    { vocab: ["なのか"], meaning: ["7th day"] },
    { vocab: ["ようか"], meaning: ["8th day"] },
    { vocab: ["ここのか"], meaning: ["9th day"] },
    { vocab: ["とおか"], meaning: ["10th day"] },
    { vocab: ["はつか"], meaning: ["20th day"] },
    { vocab: ["つき"], meaning: ["month"] },
    { vocab: ["いちがつ"], meaning: ["january"] },
    { vocab: ["にがつ"], meaning: ["february"] },
    { vocab: ["さんがつ"], meaning: ["march"] },
    { vocab: ["しがつ"], meaning: ["april"] },
    { vocab: ["ごがつ"], meaning: ["may"] },
    { vocab: ["ろくがつ"], meaning: ["june"] },
    { vocab: ["しちがつ"], meaning: ["july"] },
    { vocab: ["はちがつ"], meaning: ["august"] },
    { vocab: ["くがつ"], meaning: ["september"] },
    { vocab: ["じゅうがつ"], meaning: ["october"] },
    { vocab: ["じゅういちがつ"], meaning: ["november"] },
    { vocab: ["じゅうにがつ"], meaning: ["december"] },
    { vocab: ["せんせんげつ"], meaning: ["month before last"] },
    { vocab: ["せんげつ"], meaning: ["last month"] },
    { vocab: ["こんげつ"], meaning: ["this month"] },
    { vocab: ["らいげつ"], meaning: ["next month"] },
    { vocab: ["さらいげつ"], meaning: ["month after next"] },
    { vocab: ["おととし"], meaning: ["year before last"] },
    { vocab: ["きょねん"], meaning: ["last year"] },
    { vocab: ["ことし"], meaning: ["this year"] },
    { vocab: ["らいねん"], meaning: ["next year"] },
    { vocab: ["さらいねん"], meaning: ["year after next"] },
    { vocab: ["いつ"], meaning: ["when"] },
    { vocab: ["なんようび"], meaning: ["what day"] },
    { vocab: ["なんねん"], meaning: ["what year", "how many years"] },
    { vocab: ["なんさい"], meaning: ["how old"] },
    { vocab: ["いきます"], meaning: ["go"] },
    { vocab: ["かいます"], meaning: ["buy"] },
    { vocab: ["とります"], meaning: ["take"] },
    { vocab: ["わかります"], meaning: ["understand"] },
    { vocab: ["かえります"], meaning: ["return"] },
    { vocab: ["きます"], meaning: ["come"] },
    { vocab: ["おなじ"], meaning: ["same"] },
    { vocab: ["いっしょに"], meaning: ["together"] },
    { vocab: ["じゅうはっさい"], meaning: ["18 years old"] }
  ],
  5: [
    { vocab: ["しゅくだい"], meaning: ["homework"] },
    { vocab: ["てら"], meaning: ["temple"] },
    { vocab: ["えき"], meaning: ["train station"] },
    { vocab: ["ひこうき"], meaning: ["airplane"] },
    { vocab: ["しんかんせん"], meaning: ["bullet train"] },
    { vocab: ["ふね"], meaning: ["ship", "boat"] },
    { vocab: ["でんしゃ"], meaning: ["electric train"] },
    { vocab: ["ごぜん"], meaning: ["am"] },
    { vocab: ["ごご"], meaning: ["pm"] },
    { vocab: ["あさはやく"], meaning: ["early in the morning"] },
    { vocab: ["よるおそく"], meaning: ["late at night"] },
    { vocab: ["はるやすみ"], meaning: ["spring vacation"] },
    { vocab: ["なつやすみ"], meaning: ["summer vacation"] },
    { vocab: ["あきやすみ"], meaning: ["autumn vacation"] },
    { vocab: ["ふゆやすみ"], meaning: ["winter vacation"] },
    { vocab: ["いちにち"], meaning: ["one day"] },
    { vocab: ["ゆうべ"], meaning: ["last night"] },
    { vocab: ["けさ"], meaning: ["this morning"] },
    { vocab: ["こんばん"], meaning: ["this evening"] },
    { vocab: ["うんどう"], meaning: ["exercise"] },
    { vocab: ["りょこう"], meaning: ["trip"] },
    { vocab: ["けんぶつ"], meaning: ["sightseeing"] },
    { vocab: ["どう"], meaning: ["how"] },
    { vocab: ["どのぐらい"], meaning: ["how much"] },
    { vocab: ["かかります"], meaning: ["require", "cost", "take"] },
    { vocab: ["いそがしい"], meaning: ["busy"] },
    { vocab: ["むずかしい"], meaning: ["difficult", "hard"] },
    { vocab: ["やさしい"], meaning: ["easy"] },
    { vocab: ["たのしい"], meaning: ["enjoyable", "pleasant", "fun"] },
    { vocab: ["ちかい"], meaning: ["near"] },
    { vocab: ["とおい"], meaning: ["far"] },
    { vocab: ["ながい"], meaning: ["long"] },
    { vocab: ["みじかい"], meaning: ["short"] },
    { vocab: ["さむい"], meaning: ["cold"] },
    { vocab: ["あつい"], meaning: ["hot"] },
    { vocab: ["おそい"], meaning: ["late"] },
    { vocab: ["はやい"], meaning: ["early", "fast"] },
    { vocab: ["とても"], meaning: ["very", "extremely", "terribly"] },
    { vocab: ["たくさん"], meaning: ["much", "many", "a lot"] },
    { vocab: ["あまり"], meaning: ["not very"] },
    { vocab: ["あるいて"], meaning: ["on foot"] },
    { vocab: ["すこし"], meaning: ["a little", "a few"] },
    { vocab: ["それから"], meaning: ["and then", "after that"] },
    { vocab: ["でも", "しかし"], meaning: ["but", "however"] },
    { vocab: ["など"], meaning: ["etc"] },
    { vocab: ["か"], meaning: ["or"] },
    { vocab: ["いちじかん"], meaning: ["1 hour"] },
    { vocab: ["みっかかん"], meaning: ["3 days"] },
    { vocab: ["いっしゅうかん"], meaning: ["1 week"] },
    { vocab: ["いっかげつ"], meaning: ["1 month"] },
    { vocab: ["いちびょう"], meaning: ["1 second"] }
  ],
  6: [
    { vocab: ["まち"], meaning: ["city", "town"] },
    { vocab: ["なか"], meaning: ["inside"] },
    { vocab: ["かいもの"], meaning: ["shopping"] },
    { vocab: ["ビル"], meaning: ["building"] },
    { vocab: ["いっかい"], meaning: ["1st floor"] },
    { vocab: ["かいものきゃく"], meaning: ["shoppers", "customers"] },
    { vocab: ["たな"], meaning: ["shelf"] },
    { vocab: ["うしろ"], meaning: ["back", "behind"] },
    { vocab: ["はこ"], meaning: ["box"] },
    { vocab: ["おつり"], meaning: ["monetary change"] },
    { vocab: ["もん"], meaning: ["gate"] },
    { vocab: ["そば"], meaning: ["near", "nearby"] },
    { vocab: ["いけ"], meaning: ["pond"] },
    { vocab: ["そと"], meaning: ["outside"] },
    { vocab: ["き"], meaning: ["tree"] },
    { vocab: ["ふくろ"], meaning: ["purses", "sacks"] },
    { vocab: ["みかん"], meaning: ["mandarin orange", "tangerine"] },
    { vocab: ["りんご"], meaning: ["apple"] },
    { vocab: ["まえ"], meaning: ["front"] },
    { vocab: ["うえ"], meaning: ["top", "over", "above"] },
    { vocab: ["した"], meaning: ["under", "below"] },
    { vocab: ["よこ"], meaning: ["beside", "side"] },
    { vocab: ["むこう"], meaning: ["beyond", "over there"] },
    { vocab: ["あいだ"], meaning: ["in between"] },
    { vocab: ["うま"], meaning: ["horse"] },
    { vocab: ["うし"], meaning: ["cow"] },
    { vocab: ["いぬ"], meaning: ["dog"] },
    { vocab: ["ねこ"], meaning: ["cat"] },
    { vocab: ["とり"], meaning: ["bird"] },
    { vocab: ["かさ"], meaning: ["umbrella"] },
    { vocab: ["おかね"], meaning: ["money"] },
    { vocab: ["デパート"], meaning: ["department store"] },
    { vocab: ["はな"], meaning: ["flower"] },
    { vocab: ["がいこくじん"], meaning: ["foreigner"] },
    { vocab: ["ひとり"], meaning: ["one person"] },
    { vocab: ["ふたり"], meaning: ["two people"] },
    { vocab: ["ひとつ"], meaning: ["one"] },
    { vocab: ["ふたつ"], meaning: ["two"] },
    { vocab: ["みっつ"], meaning: ["three"] },
    { vocab: ["よっつ"], meaning: ["four"] },
    { vocab: ["いつつ"], meaning: ["five"] },
    { vocab: ["むっつ"], meaning: ["six"] },
    { vocab: ["ななつ"], meaning: ["seven"] },
    { vocab: ["やっつ"], meaning: ["eight"] },
    { vocab: ["ここのつ"], meaning: ["nine"] },
    { vocab: ["とお"], meaning: ["ten"] },
    { vocab: ["いくつ"], meaning: ["how many"] },
    { vocab: ["なにか"], meaning: ["something"] },
    { vocab: ["なにも"], meaning: ["nothing"] },
    { vocab: ["だれも"], meaning: ["nobody"] },
    { vocab: ["だれか"], meaning: ["someone", "somebody"] },
    { vocab: ["あります"], meaning: ["exist (non-living)", "have"] },
    { vocab: ["います"], meaning: ["exist (living)"] },
    { vocab: ["やすみます"], meaning: ["rest"] },
    { vocab: ["ください"], meaning: ["please give me"] },
    { vocab: ["いろいろな"], meaning: ["various kind of"] },
    { vocab: ["しずかな"], meaning: ["quiet"] },
    { vocab: ["きれいな"], meaning: ["pretty", "beautiful"] },
    { vocab: ["じょうぶな"], meaning: ["sturdy", "strong", "durable"] },
    { vocab: ["ひまな"], meaning: ["having leisure time"] },
    { vocab: ["ひとりも"], meaning: ["not even one person"] },
    { vocab: ["ぜんぶ"], meaning: ["all", "everything"] },
    { vocab: ["おおぜい"], meaning: ["a lot of people"] },
    { vocab: ["すこしも"], meaning: ["not at all"] },
    { vocab: ["じゃ","では"], meaning: ["then", "well then"] },
    { vocab: ["だけ"], meaning: ["only"] },
    { vocab: ["ぜんぶで"], meaning: ["in all"] },
    { vocab: ["いらっしゃいませ"], meaning: ["welcome", "may i help you"] },
    { vocab: ["いちまい"], meaning: ["one (flat object)"] },
    { vocab: ["いちだい"], meaning: ["one (machine, car)"] },
    { vocab: ["にほん"], meaning: ["two (long objects)"] },
    { vocab: ["さんぼん"], meaning: ["three (long objects)"] },
    { vocab: ["いっぽん"], meaning: ["one (long object)"] },
    { vocab: ["にひき"], meaning: ["two (small animals)"] },
    { vocab: ["さんびき"], meaning: ["three (small animals)"] },
    { vocab: ["いっぴき"], meaning: ["one (small animal)"] },
    { vocab: ["にはい"], meaning: ["two (cups or bowls)"] },
    { vocab: ["さんばい"], meaning: ["three (cups or bowls)"] },
    { vocab: ["いっぱい"], meaning: ["one (cup or bowl)"] },
    { vocab: ["いっさつ"], meaning: ["one volume"] },
    { vocab: ["さんにん"], meaning: ["three people"] },
    { vocab: ["さんがい"], meaning: ["third floor"] }
  ],
  7 : [
    { vocab: ["てんき"], meaning: ["weather"] },
    { vocab: ["あめ"], meaning: ["rain"] },
    { vocab: ["かぜ"], meaning: ["wind"] },
    { vocab: ["ゆき"], meaning: ["snow"] },
    { vocab: ["そら"], meaning: ["sky"] },
    { vocab: ["かわ"], meaning: ["river"] },
    { vocab: ["みず"], meaning: ["water"] },
    { vocab: ["て"], meaning: ["hand"] },
    { vocab: ["はやし"], meaning: ["woods", "grove"] },
    { vocab: ["ひるごはん"], meaning: ["lunch"] },
    { vocab: ["おちゃ"], meaning: ["tea"] },
    { vocab: ["びょうき"], meaning: ["illness", "sickness"] },
    { vocab: ["きた"], meaning: ["north"] },
    { vocab: ["ひがし"], meaning: ["east"] },
    { vocab: ["にし"], meaning: ["west"] },
    { vocab: ["みなみ"], meaning: ["south"] },
    { vocab: ["どちら"], meaning: ["which side", "which way"] },
    { vocab: ["こちら"], meaning: ["this way"] },
    { vocab: ["そちら"], meaning: ["that way"] },
    { vocab: ["あちら"], meaning: ["that way (far)"] },
    { vocab: ["なります"], meaning: ["become", "be"] },
    { vocab: ["ふります"], meaning: ["fall (rain, snow)"] },
    { vocab: ["ふきます"], meaning: ["blow (wind)"] },
    { vocab: ["やみます"], meaning: ["stop"] },
    { vocab: ["つかれます"], meaning: ["get tired"] },
    { vocab: ["あらいます"], meaning: ["wash"] },
    { vocab: ["いい"], meaning: ["good", "fine"] },
    { vocab: ["わるい"], meaning: ["bad"] },
    { vocab: ["あつい"], meaning: ["hot"] },
    { vocab: ["つめたい"], meaning: ["cold (to touch)"] },
    { vocab: ["すずしい"], meaning: ["cool"] },
    { vocab: ["おいしい"], meaning: ["tasty", "delicious"] },
    { vocab: ["まずい"], meaning: ["bad tasting"] },
    { vocab: ["うるさい"], meaning: ["noisy"] },
    { vocab: ["おもい"], meaning: ["heavy"] },
    { vocab: ["かるい"], meaning: ["light weight"] },
    { vocab: ["ふとい"], meaning: ["thick"] },
    { vocab: ["ほそい"], meaning: ["thin"] },
    { vocab: ["つよい"], meaning: ["strong"] },
    { vocab: ["よわい"], meaning: ["weak"] },
    { vocab: ["あたたかい"], meaning: ["warm"] },
    { vocab: ["きたない"], meaning: ["dirty"] },
    { vocab: ["きれい"], meaning: ["clean"] },
    { vocab: ["げんきな"], meaning: ["health", "prep"] },
    { vocab: ["もうたべました"], meaning: ["already eaten"] },
    { vocab: ["まだたべていません"], meaning: ["not eaten yet"] },
    { vocab: ["いつも"], meaning: ["always"] },
    { vocab: ["いちばん"], meaning: ["the most"] },
    { vocab: ["みなさん"], meaning: ["all", "everyone"] },
    { vocab: ["よかったですね"], meaning: ["that was good, wasn’t it?"] },
    { vocab: ["どうもすみません"], meaning: ["thank you very much", "sorry"] },
    { vocab: ["いただきます"], meaning: ["let’s eat", "thanks for the meal"] },
    { vocab: ["じゅう"], meaning: ["throughout"] }
  ],
  
  
}